name: Build and Deploy
on:
  # every day
  # schedule: 
    # - cron: '0 0 * * *'
  # or on push
  push:
    branches:
    - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/setup-node@v1
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
      if: steps.cache.outputs.cache-hit != 'true'
    - run: yarn build
      env: 
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}